# Generated by Django 3.1.2 on 2020-11-12 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('precio_total', models.IntegerField()),
                ('fecha', models.DateField()),
                ('id_carrito_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.carrito')),
            ],
        ),
        migrations.CreateModel(
            name='repartidor',
            fields=[
                ('id_repartidor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='metodo_pago',
            fields=[
                ('id_metodo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_metodo', models.CharField(max_length=45)),
                ('id_factura_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.factura')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='id_repartidor_repartidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.repartidor'),
        ),
        migrations.CreateModel(
            name='factura_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_total', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('id_factura_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.factura')),
                ('id_producto_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
            options={
                'unique_together': {('id_factura_factura', 'id_producto_producto')},
            },
        ),
    ]
