# Generated by Django 3.1.2 on 2020-11-12 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('direccion_correo', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='telefono',
            fields=[
                ('id_telefono', models.AutoField(primary_key=True, serialize=False)),
                ('num_telefono', models.IntegerField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('via', models.CharField(max_length=45)),
                ('num_principal', models.SmallIntegerField()),
                ('sufijo1', models.CharField(max_length=45)),
                ('num_secundario', models.SmallIntegerField()),
                ('sufijo2', models.CharField(max_length=45)),
                ('num_terciario', models.SmallIntegerField()),
                ('otro', models.CharField(max_length=70)),
                ('id_ciudad_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='calle_direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('id_direccion_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.direccion')),
            ],
            options={
                'unique_together': {('id_cliente_cliente', 'id_direccion_direccion')},
            },
        ),
    ]
